#############################################################################
# Makefile for building: SMSAM
# Generated by qmake (3.0) (Qt 5.3.2)
# Project:  SMSAM.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt5/bin/qmake -spec linux-g++ -o Makefile SMSAM.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -w -D_REENTRANT -fPIE $(DEFINES)
CXXFLAGS      = -pipe -O2 -w -D_REENTRANT -fPIE $(DEFINES)
INCPATH       = -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I. -IEigen -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) -lQt5PrintSupport -L/usr/X11R6/lib64 -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/x86_64-linux-gnu/qt5/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = mainwindow.C \
		main.C \
		formloadmatrix.C \
		formviewmatrix.C \
		stackwidget.C \
		accountwidget.C \
		formvariablesexogenas.cpp \
		stackvariablesexogenas.cpp \
		variableexogenawidget.cpp \
		formexportmatrix.cpp \
		formencadenamientos.cpp \
		stackencadenamientos.cpp \
		encadenamientoswidget.cpp \
		formcompararresultados.cpp \
		formcompararmnc.cpp \
		formincidenciai.cpp \
		formpreciosnohomogeneos.cpp \
		stackpreciosnohomogeneos.cpp \
		variablepnh.cpp \
		genericFunctions.cpp \
		formexportreport.cpp \
		qcustomplot.cpp \
		formdescomposicion.cpp qrc_images.cpp \
		moc_mainwindow.cpp \
		moc_formloadmatrix.cpp \
		moc_formviewmatrix.cpp \
		moc_stackwidget.cpp \
		moc_accountwidget.cpp \
		moc_formvariablesexogenas.cpp \
		moc_stackvariablesexogenas.cpp \
		moc_variableexogenawidget.cpp \
		moc_formexportmatrix.cpp \
		moc_formencadenamientos.cpp \
		moc_stackencadenamientos.cpp \
		moc_encadenamientoswidget.cpp \
		moc_formcompararresultados.cpp \
		moc_formcompararmnc.cpp \
		moc_formincidenciai.cpp \
		moc_formpreciosnohomogeneos.cpp \
		moc_stackpreciosnohomogeneos.cpp \
		moc_variablepnh.cpp \
		moc_formexportreport.cpp \
		moc_qcustomplot.cpp \
		moc_formdescomposicion.cpp
OBJECTS       = mainwindow.o \
		main.o \
		formloadmatrix.o \
		formviewmatrix.o \
		stackwidget.o \
		accountwidget.o \
		formvariablesexogenas.o \
		stackvariablesexogenas.o \
		variableexogenawidget.o \
		formexportmatrix.o \
		formencadenamientos.o \
		stackencadenamientos.o \
		encadenamientoswidget.o \
		formcompararresultados.o \
		formcompararmnc.o \
		formincidenciai.o \
		formpreciosnohomogeneos.o \
		stackpreciosnohomogeneos.o \
		variablepnh.o \
		genericFunctions.o \
		formexportreport.o \
		qcustomplot.o \
		formdescomposicion.o \
		qrc_images.o \
		moc_mainwindow.o \
		moc_formloadmatrix.o \
		moc_formviewmatrix.o \
		moc_stackwidget.o \
		moc_accountwidget.o \
		moc_formvariablesexogenas.o \
		moc_stackvariablesexogenas.o \
		moc_variableexogenawidget.o \
		moc_formexportmatrix.o \
		moc_formencadenamientos.o \
		moc_stackencadenamientos.o \
		moc_encadenamientoswidget.o \
		moc_formcompararresultados.o \
		moc_formcompararmnc.o \
		moc_formincidenciai.o \
		moc_formpreciosnohomogeneos.o \
		moc_stackpreciosnohomogeneos.o \
		moc_variablepnh.o \
		moc_formexportreport.o \
		moc_qcustomplot.o \
		moc_formdescomposicion.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/shell-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_off.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		SMSAM.pro mainwindow.C \
		main.C \
		formloadmatrix.C \
		formviewmatrix.C \
		stackwidget.C \
		accountwidget.C \
		formvariablesexogenas.cpp \
		stackvariablesexogenas.cpp \
		variableexogenawidget.cpp \
		formexportmatrix.cpp \
		formencadenamientos.cpp \
		stackencadenamientos.cpp \
		encadenamientoswidget.cpp \
		formcompararresultados.cpp \
		formcompararmnc.cpp \
		formincidenciai.cpp \
		formpreciosnohomogeneos.cpp \
		stackpreciosnohomogeneos.cpp \
		variablepnh.cpp \
		genericFunctions.cpp \
		formexportreport.cpp \
		qcustomplot.cpp \
		formdescomposicion.cpp
QMAKE_TARGET  = SMSAM
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = SMSAM


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_formLoadMatrix.h ui_formvariablesexogenas.h ui_formexportmatrix.h ui_formencadenamientos.h ui_formcompararresultados.h ui_formcompararmnc.h ui_formincidenciai.h ui_formpreciosnohomogeneos.h ui_formexportreport.h ui_formViewMatrix.h ui_formdescomposicion.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: SMSAM.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/shell-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_off.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		SMSAM.pro \
		img/images.qrc \
		/usr/lib/x86_64-linux-gnu/libQt5PrintSupport.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Gui.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Core.prl
	$(QMAKE) -spec linux-g++ -o Makefile SMSAM.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/shell-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_off.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
SMSAM.pro:
img/images.qrc:
/usr/lib/x86_64-linux-gnu/libQt5PrintSupport.prl:
/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl:
/usr/lib/x86_64-linux-gnu/libQt5Gui.prl:
/usr/lib/x86_64-linux-gnu/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -spec linux-g++ -o Makefile SMSAM.pro

qmake_all: FORCE

dist: 
	@test -d .tmp/SMSAM1.0.0 || mkdir -p .tmp/SMSAM1.0.0
	$(COPY_FILE) --parents $(DIST) .tmp/SMSAM1.0.0/ && $(COPY_FILE) --parents img/images.qrc .tmp/SMSAM1.0.0/ && $(COPY_FILE) --parents mainwindow.H formloadmatrix.H formviewmatrix.H stackwidget.H accountwidget.H formvariablesexogenas.h stackvariablesexogenas.h variableexogenawidget.h formexportmatrix.h formencadenamientos.h stackencadenamientos.h encadenamientoswidget.h formcompararresultados.h formcompararmnc.h formincidenciai.h formpreciosnohomogeneos.h stackpreciosnohomogeneos.h variablepnh.h genericFunctions.h formexportreport.h qcustomplot.h formdescomposicion.h .tmp/SMSAM1.0.0/ && $(COPY_FILE) --parents mainwindow.C main.C formloadmatrix.C formviewmatrix.C stackwidget.C accountwidget.C formvariablesexogenas.cpp stackvariablesexogenas.cpp variableexogenawidget.cpp formexportmatrix.cpp formencadenamientos.cpp stackencadenamientos.cpp encadenamientoswidget.cpp formcompararresultados.cpp formcompararmnc.cpp formincidenciai.cpp formpreciosnohomogeneos.cpp stackpreciosnohomogeneos.cpp variablepnh.cpp genericFunctions.cpp formexportreport.cpp qcustomplot.cpp formdescomposicion.cpp .tmp/SMSAM1.0.0/ && $(COPY_FILE) --parents formLoadMatrix.ui formvariablesexogenas.ui formexportmatrix.ui formencadenamientos.ui formcompararresultados.ui formcompararmnc.ui formincidenciai.ui formpreciosnohomogeneos.ui formexportreport.ui formViewMatrix.ui formdescomposicion.ui .tmp/SMSAM1.0.0/ && (cd `dirname .tmp/SMSAM1.0.0` && $(TAR) SMSAM1.0.0.tar SMSAM1.0.0 && $(COMPRESS) SMSAM1.0.0.tar) && $(MOVE) `dirname .tmp/SMSAM1.0.0`/SMSAM1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/SMSAM1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all: qrc_images.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_images.cpp
qrc_images.cpp: img/images.qrc \
		img/folder_blue.png \
		img/Imagen-matriz.png \
		img/edit-deshabilitado.png \
		img/edit-habilitado.png \
		img/logo_cenditel.jpg \
		img/estructura_matriz.jpg \
		img/undo-habilitado.png
	/usr/lib/x86_64-linux-gnu/qt5/bin/rcc -name images img/images.qrc -o qrc_images.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp moc_formloadmatrix.cpp moc_formviewmatrix.cpp moc_stackwidget.cpp moc_accountwidget.cpp moc_formvariablesexogenas.cpp moc_stackvariablesexogenas.cpp moc_variableexogenawidget.cpp moc_formexportmatrix.cpp moc_formencadenamientos.cpp moc_stackencadenamientos.cpp moc_encadenamientoswidget.cpp moc_formcompararresultados.cpp moc_formcompararmnc.cpp moc_formincidenciai.cpp moc_formpreciosnohomogeneos.cpp moc_stackpreciosnohomogeneos.cpp moc_variablepnh.cpp moc_formexportreport.cpp moc_qcustomplot.cpp moc_formdescomposicion.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_formloadmatrix.cpp moc_formviewmatrix.cpp moc_stackwidget.cpp moc_accountwidget.cpp moc_formvariablesexogenas.cpp moc_stackvariablesexogenas.cpp moc_variableexogenawidget.cpp moc_formexportmatrix.cpp moc_formencadenamientos.cpp moc_stackencadenamientos.cpp moc_encadenamientoswidget.cpp moc_formcompararresultados.cpp moc_formcompararmnc.cpp moc_formincidenciai.cpp moc_formpreciosnohomogeneos.cpp moc_stackpreciosnohomogeneos.cpp moc_variablepnh.cpp moc_formexportreport.cpp moc_qcustomplot.cpp moc_formdescomposicion.cpp
moc_mainwindow.cpp: formloadmatrix.H \
		ui_formLoadMatrix.h \
		formviewmatrix.H \
		formvariablesexogenas.h \
		formexportmatrix.h \
		formencadenamientos.h \
		ui_formcompararresultados.h \
		formcompararresultados.h \
		ui_formcompararmnc.h \
		formcompararmnc.h \
		ui_formincidenciai.h \
		formincidenciai.h \
		formpreciosnohomogeneos.h \
		formexportreport.h \
		ui_formexportreport.h \
		genericFunctions.h \
		qcustomplot.h \
		accountwidget.H \
		formdescomposicion.h \
		stackwidget.H \
		stackvariablesexogenas.h \
		variableexogenawidget.h \
		stackencadenamientos.h \
		encadenamientoswidget.h \
		stackpreciosnohomogeneos.h \
		variablepnh.h \
		Eigen/Eigen \
		Eigen/Dense \
		Eigen/Core \
		Eigen/src/Core/util/DisableStupidWarnings.h \
		Eigen/src/Core/util/Macros.h \
		Eigen/src/Core/util/MKL_support.h \
		Eigen/src/Core/util/Constants.h \
		Eigen/src/Core/util/ForwardDeclarations.h \
		Eigen/src/Core/util/Meta.h \
		Eigen/src/Core/util/StaticAssert.h \
		Eigen/src/Core/util/XprHelper.h \
		Eigen/src/Core/util/Memory.h \
		Eigen/src/Core/NumTraits.h \
		Eigen/src/Core/MathFunctions.h \
		Eigen/src/Core/GenericPacketMath.h \
		Eigen/src/Core/arch/SSE/PacketMath.h \
		Eigen/src/Core/arch/SSE/MathFunctions.h \
		Eigen/src/Core/arch/SSE/Complex.h \
		Eigen/src/Core/arch/AltiVec/PacketMath.h \
		Eigen/src/Core/arch/AltiVec/Complex.h \
		Eigen/src/Core/arch/NEON/PacketMath.h \
		Eigen/src/Core/arch/NEON/Complex.h \
		Eigen/src/Core/arch/Default/Settings.h \
		Eigen/src/Core/Functors.h \
		Eigen/src/Core/DenseCoeffsBase.h \
		Eigen/src/Core/DenseBase.h \
		Eigen/src/plugins/BlockMethods.h \
		Eigen/src/Core/MatrixBase.h \
		Eigen/src/plugins/CommonCwiseUnaryOps.h \
		Eigen/src/plugins/CommonCwiseBinaryOps.h \
		Eigen/src/plugins/MatrixCwiseUnaryOps.h \
		Eigen/src/plugins/MatrixCwiseBinaryOps.h \
		Eigen/src/Core/EigenBase.h \
		Eigen/src/Core/Assign.h \
		Eigen/src/Core/util/BlasUtil.h \
		Eigen/src/Core/DenseStorage.h \
		Eigen/src/Core/NestByValue.h \
		Eigen/src/Core/ForceAlignedAccess.h \
		Eigen/src/Core/ReturnByValue.h \
		Eigen/src/Core/NoAlias.h \
		Eigen/src/Core/PlainObjectBase.h \
		Eigen/src/Core/Matrix.h \
		Eigen/src/Core/Array.h \
		Eigen/src/Core/CwiseBinaryOp.h \
		Eigen/src/Core/CwiseUnaryOp.h \
		Eigen/src/Core/CwiseNullaryOp.h \
		Eigen/src/Core/CwiseUnaryView.h \
		Eigen/src/Core/SelfCwiseBinaryOp.h \
		Eigen/src/Core/Dot.h \
		Eigen/src/Core/StableNorm.h \
		Eigen/src/Core/MapBase.h \
		Eigen/src/Core/Stride.h \
		Eigen/src/Core/Map.h \
		Eigen/src/Core/Block.h \
		Eigen/src/Core/VectorBlock.h \
		Eigen/src/Core/Ref.h \
		Eigen/src/Core/Transpose.h \
		Eigen/src/Core/DiagonalMatrix.h \
		Eigen/src/Core/Diagonal.h \
		Eigen/src/Core/DiagonalProduct.h \
		Eigen/src/Core/PermutationMatrix.h \
		Eigen/src/Core/Transpositions.h \
		Eigen/src/Core/Redux.h \
		Eigen/src/Core/Visitor.h \
		Eigen/src/Core/Fuzzy.h \
		Eigen/src/Core/IO.h \
		Eigen/src/Core/Swap.h \
		Eigen/src/Core/CommaInitializer.h \
		Eigen/src/Core/Flagged.h \
		Eigen/src/Core/ProductBase.h \
		Eigen/src/Core/GeneralProduct.h \
		Eigen/src/Core/TriangularMatrix.h \
		Eigen/src/Core/SelfAdjointView.h \
		Eigen/src/Core/products/GeneralBlockPanelKernel.h \
		Eigen/src/Core/products/Parallelizer.h \
		Eigen/src/Core/products/CoeffBasedProduct.h \
		Eigen/src/Core/products/GeneralMatrixVector.h \
		Eigen/src/Core/products/GeneralMatrixMatrix.h \
		Eigen/src/Core/SolveTriangular.h \
		Eigen/src/Core/products/GeneralMatrixMatrixTriangular.h \
		Eigen/src/Core/products/SelfadjointMatrixVector.h \
		Eigen/src/Core/products/SelfadjointMatrixMatrix.h \
		Eigen/src/Core/products/SelfadjointProduct.h \
		Eigen/src/Core/products/SelfadjointRank2Update.h \
		Eigen/src/Core/products/TriangularMatrixVector.h \
		Eigen/src/Core/products/TriangularMatrixMatrix.h \
		Eigen/src/Core/products/TriangularSolverMatrix.h \
		Eigen/src/Core/products/TriangularSolverVector.h \
		Eigen/src/Core/BandMatrix.h \
		Eigen/src/Core/CoreIterators.h \
		Eigen/src/Core/BooleanRedux.h \
		Eigen/src/Core/Select.h \
		Eigen/src/Core/VectorwiseOp.h \
		Eigen/src/Core/Random.h \
		Eigen/src/Core/Replicate.h \
		Eigen/src/Core/Reverse.h \
		Eigen/src/Core/ArrayBase.h \
		Eigen/src/plugins/ArrayCwiseUnaryOps.h \
		Eigen/src/plugins/ArrayCwiseBinaryOps.h \
		Eigen/src/Core/ArrayWrapper.h \
		Eigen/src/Core/products/GeneralMatrixMatrix_MKL.h \
		Eigen/src/Core/products/GeneralMatrixVector_MKL.h \
		Eigen/src/Core/products/GeneralMatrixMatrixTriangular_MKL.h \
		Eigen/src/Core/products/SelfadjointMatrixMatrix_MKL.h \
		Eigen/src/Core/products/SelfadjointMatrixVector_MKL.h \
		Eigen/src/Core/products/TriangularMatrixMatrix_MKL.h \
		Eigen/src/Core/products/TriangularMatrixVector_MKL.h \
		Eigen/src/Core/products/TriangularSolverMatrix_MKL.h \
		Eigen/src/Core/Assign_MKL.h \
		Eigen/src/Core/GlobalFunctions.h \
		Eigen/src/Core/util/ReenableStupidWarnings.h \
		Eigen/Eigen2Support \
		Eigen/src/Eigen2Support/Macros.h \
		Eigen/src/Eigen2Support/Memory.h \
		Eigen/src/Eigen2Support/Meta.h \
		Eigen/src/Eigen2Support/Lazy.h \
		Eigen/src/Eigen2Support/Cwise.h \
		Eigen/src/Eigen2Support/CwiseOperators.h \
		Eigen/src/Eigen2Support/TriangularSolver.h \
		Eigen/src/Eigen2Support/Block.h \
		Eigen/src/Eigen2Support/VectorBlock.h \
		Eigen/src/Eigen2Support/Minor.h \
		Eigen/src/Eigen2Support/MathFunctions.h \
		Eigen/LU \
		Eigen/src/misc/Solve.h \
		Eigen/src/misc/Kernel.h \
		Eigen/src/misc/Image.h \
		Eigen/src/LU/FullPivLU.h \
		Eigen/src/LU/PartialPivLU.h \
		Eigen/src/LU/PartialPivLU_MKL.h \
		Eigen/src/LU/Determinant.h \
		Eigen/src/LU/Inverse.h \
		Eigen/src/LU/arch/Inverse_SSE.h \
		Eigen/src/Eigen2Support/LU.h \
		Eigen/Cholesky \
		Eigen/src/Cholesky/LLT.h \
		Eigen/src/Cholesky/LDLT.h \
		Eigen/src/Cholesky/LLT_MKL.h \
		Eigen/QR \
		Eigen/Jacobi \
		Eigen/src/Jacobi/Jacobi.h \
		Eigen/Householder \
		Eigen/src/Householder/Householder.h \
		Eigen/src/Householder/HouseholderSequence.h \
		Eigen/src/Householder/BlockHouseholder.h \
		Eigen/src/QR/HouseholderQR.h \
		Eigen/src/QR/FullPivHouseholderQR.h \
		Eigen/src/QR/ColPivHouseholderQR.h \
		Eigen/src/QR/HouseholderQR_MKL.h \
		Eigen/src/QR/ColPivHouseholderQR_MKL.h \
		Eigen/src/Eigen2Support/QR.h \
		Eigen/Eigenvalues \
		Eigen/Geometry \
		Eigen/SVD \
		Eigen/src/SVD/JacobiSVD.h \
		Eigen/src/SVD/JacobiSVD_MKL.h \
		Eigen/src/SVD/UpperBidiagonalization.h \
		Eigen/src/Eigen2Support/SVD.h \
		Eigen/src/Geometry/OrthoMethods.h \
		Eigen/src/Geometry/EulerAngles.h \
		Eigen/src/Geometry/Homogeneous.h \
		Eigen/src/Geometry/RotationBase.h \
		Eigen/src/Geometry/Rotation2D.h \
		Eigen/src/Geometry/Quaternion.h \
		Eigen/src/Geometry/AngleAxis.h \
		Eigen/src/Geometry/Transform.h \
		Eigen/src/Geometry/Translation.h \
		Eigen/src/Geometry/Scaling.h \
		Eigen/src/Geometry/Hyperplane.h \
		Eigen/src/Geometry/ParametrizedLine.h \
		Eigen/src/Geometry/AlignedBox.h \
		Eigen/src/Geometry/Umeyama.h \
		Eigen/src/Geometry/arch/Geometry_SSE.h \
		Eigen/src/Eigen2Support/Geometry/All.h \
		Eigen/src/Eigen2Support/Geometry/RotationBase.h \
		Eigen/src/Eigen2Support/Geometry/Rotation2D.h \
		Eigen/src/Eigen2Support/Geometry/Quaternion.h \
		Eigen/src/Eigen2Support/Geometry/AngleAxis.h \
		Eigen/src/Eigen2Support/Geometry/Transform.h \
		Eigen/src/Eigen2Support/Geometry/Translation.h \
		Eigen/src/Eigen2Support/Geometry/Scaling.h \
		Eigen/src/Eigen2Support/Geometry/AlignedBox.h \
		Eigen/src/Eigen2Support/Geometry/Hyperplane.h \
		Eigen/src/Eigen2Support/Geometry/ParametrizedLine.h \
		Eigen/src/Eigenvalues/Tridiagonalization.h \
		Eigen/src/Eigenvalues/RealSchur.h \
		Eigen/src/Eigenvalues/HessenbergDecomposition.h \
		Eigen/src/Eigenvalues/EigenSolver.h \
		Eigen/src/Eigenvalues/SelfAdjointEigenSolver.h \
		Eigen/src/Eigenvalues/GeneralizedSelfAdjointEigenSolver.h \
		Eigen/src/Eigenvalues/ComplexSchur.h \
		Eigen/src/Eigenvalues/ComplexEigenSolver.h \
		Eigen/src/Eigenvalues/RealQZ.h \
		Eigen/src/Eigenvalues/GeneralizedEigenSolver.h \
		Eigen/src/Eigenvalues/MatrixBaseEigenvalues.h \
		Eigen/src/Eigenvalues/RealSchur_MKL.h \
		Eigen/src/Eigenvalues/ComplexSchur_MKL.h \
		Eigen/src/Eigenvalues/SelfAdjointEigenSolver_MKL.h \
		mainwindow.H
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/rodrigo/Proyectos/Matrices/mmcs -I/home/rodrigo/Proyectos/Matrices/mmcs/Eigen -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include mainwindow.H -o moc_mainwindow.cpp

moc_formloadmatrix.cpp: formloadmatrix.H
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/rodrigo/Proyectos/Matrices/mmcs -I/home/rodrigo/Proyectos/Matrices/mmcs/Eigen -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include formloadmatrix.H -o moc_formloadmatrix.cpp

moc_formviewmatrix.cpp: formviewmatrix.H
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/rodrigo/Proyectos/Matrices/mmcs -I/home/rodrigo/Proyectos/Matrices/mmcs/Eigen -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include formviewmatrix.H -o moc_formviewmatrix.cpp

moc_stackwidget.cpp: accountwidget.H \
		stackwidget.H
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/rodrigo/Proyectos/Matrices/mmcs -I/home/rodrigo/Proyectos/Matrices/mmcs/Eigen -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include stackwidget.H -o moc_stackwidget.cpp

moc_accountwidget.cpp: accountwidget.H
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/rodrigo/Proyectos/Matrices/mmcs -I/home/rodrigo/Proyectos/Matrices/mmcs/Eigen -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include accountwidget.H -o moc_accountwidget.cpp

moc_formvariablesexogenas.cpp: formvariablesexogenas.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/rodrigo/Proyectos/Matrices/mmcs -I/home/rodrigo/Proyectos/Matrices/mmcs/Eigen -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include formvariablesexogenas.h -o moc_formvariablesexogenas.cpp

moc_stackvariablesexogenas.cpp: variableexogenawidget.h \
		stackvariablesexogenas.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/rodrigo/Proyectos/Matrices/mmcs -I/home/rodrigo/Proyectos/Matrices/mmcs/Eigen -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include stackvariablesexogenas.h -o moc_stackvariablesexogenas.cpp

moc_variableexogenawidget.cpp: variableexogenawidget.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/rodrigo/Proyectos/Matrices/mmcs -I/home/rodrigo/Proyectos/Matrices/mmcs/Eigen -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include variableexogenawidget.h -o moc_variableexogenawidget.cpp

moc_formexportmatrix.cpp: formexportmatrix.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/rodrigo/Proyectos/Matrices/mmcs -I/home/rodrigo/Proyectos/Matrices/mmcs/Eigen -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include formexportmatrix.h -o moc_formexportmatrix.cpp

moc_formencadenamientos.cpp: formencadenamientos.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/rodrigo/Proyectos/Matrices/mmcs -I/home/rodrigo/Proyectos/Matrices/mmcs/Eigen -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include formencadenamientos.h -o moc_formencadenamientos.cpp

moc_stackencadenamientos.cpp: encadenamientoswidget.h \
		stackencadenamientos.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/rodrigo/Proyectos/Matrices/mmcs -I/home/rodrigo/Proyectos/Matrices/mmcs/Eigen -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include stackencadenamientos.h -o moc_stackencadenamientos.cpp

moc_encadenamientoswidget.cpp: encadenamientoswidget.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/rodrigo/Proyectos/Matrices/mmcs -I/home/rodrigo/Proyectos/Matrices/mmcs/Eigen -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include encadenamientoswidget.h -o moc_encadenamientoswidget.cpp

moc_formcompararresultados.cpp: formcompararresultados.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/rodrigo/Proyectos/Matrices/mmcs -I/home/rodrigo/Proyectos/Matrices/mmcs/Eigen -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include formcompararresultados.h -o moc_formcompararresultados.cpp

moc_formcompararmnc.cpp: formcompararmnc.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/rodrigo/Proyectos/Matrices/mmcs -I/home/rodrigo/Proyectos/Matrices/mmcs/Eigen -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include formcompararmnc.h -o moc_formcompararmnc.cpp

moc_formincidenciai.cpp: formincidenciai.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/rodrigo/Proyectos/Matrices/mmcs -I/home/rodrigo/Proyectos/Matrices/mmcs/Eigen -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include formincidenciai.h -o moc_formincidenciai.cpp

moc_formpreciosnohomogeneos.cpp: formpreciosnohomogeneos.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/rodrigo/Proyectos/Matrices/mmcs -I/home/rodrigo/Proyectos/Matrices/mmcs/Eigen -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include formpreciosnohomogeneos.h -o moc_formpreciosnohomogeneos.cpp

moc_stackpreciosnohomogeneos.cpp: variablepnh.h \
		stackpreciosnohomogeneos.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/rodrigo/Proyectos/Matrices/mmcs -I/home/rodrigo/Proyectos/Matrices/mmcs/Eigen -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include stackpreciosnohomogeneos.h -o moc_stackpreciosnohomogeneos.cpp

moc_variablepnh.cpp: variablepnh.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/rodrigo/Proyectos/Matrices/mmcs -I/home/rodrigo/Proyectos/Matrices/mmcs/Eigen -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include variablepnh.h -o moc_variablepnh.cpp

moc_formexportreport.cpp: formexportreport.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/rodrigo/Proyectos/Matrices/mmcs -I/home/rodrigo/Proyectos/Matrices/mmcs/Eigen -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include formexportreport.h -o moc_formexportreport.cpp

moc_qcustomplot.cpp: qcustomplot.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/rodrigo/Proyectos/Matrices/mmcs -I/home/rodrigo/Proyectos/Matrices/mmcs/Eigen -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include qcustomplot.h -o moc_qcustomplot.cpp

moc_formdescomposicion.cpp: formdescomposicion.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/rodrigo/Proyectos/Matrices/mmcs -I/home/rodrigo/Proyectos/Matrices/mmcs/Eigen -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include formdescomposicion.h -o moc_formdescomposicion.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_formLoadMatrix.h ui_formvariablesexogenas.h ui_formexportmatrix.h ui_formencadenamientos.h ui_formcompararresultados.h ui_formcompararmnc.h ui_formincidenciai.h ui_formpreciosnohomogeneos.h ui_formexportreport.h ui_formViewMatrix.h ui_formdescomposicion.h
compiler_uic_clean:
	-$(DEL_FILE) ui_formLoadMatrix.h ui_formvariablesexogenas.h ui_formexportmatrix.h ui_formencadenamientos.h ui_formcompararresultados.h ui_formcompararmnc.h ui_formincidenciai.h ui_formpreciosnohomogeneos.h ui_formexportreport.h ui_formViewMatrix.h ui_formdescomposicion.h
ui_formLoadMatrix.h: formLoadMatrix.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic formLoadMatrix.ui -o ui_formLoadMatrix.h

ui_formvariablesexogenas.h: formvariablesexogenas.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic formvariablesexogenas.ui -o ui_formvariablesexogenas.h

ui_formexportmatrix.h: formexportmatrix.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic formexportmatrix.ui -o ui_formexportmatrix.h

ui_formencadenamientos.h: formencadenamientos.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic formencadenamientos.ui -o ui_formencadenamientos.h

ui_formcompararresultados.h: formcompararresultados.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic formcompararresultados.ui -o ui_formcompararresultados.h

ui_formcompararmnc.h: formcompararmnc.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic formcompararmnc.ui -o ui_formcompararmnc.h

ui_formincidenciai.h: formincidenciai.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic formincidenciai.ui -o ui_formincidenciai.h

ui_formpreciosnohomogeneos.h: formpreciosnohomogeneos.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic formpreciosnohomogeneos.ui -o ui_formpreciosnohomogeneos.h

ui_formexportreport.h: formexportreport.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic formexportreport.ui -o ui_formexportreport.h

ui_formViewMatrix.h: formViewMatrix.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic formViewMatrix.ui -o ui_formViewMatrix.h

ui_formdescomposicion.h: formdescomposicion.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic formdescomposicion.ui -o ui_formdescomposicion.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

mainwindow.o: mainwindow.C mainwindow.H \
		formloadmatrix.H \
		ui_formLoadMatrix.h \
		formviewmatrix.H \
		formvariablesexogenas.h \
		formexportmatrix.h \
		formencadenamientos.h \
		ui_formcompararresultados.h \
		formcompararresultados.h \
		ui_formcompararmnc.h \
		formcompararmnc.h \
		ui_formincidenciai.h \
		formincidenciai.h \
		formpreciosnohomogeneos.h \
		formexportreport.h \
		ui_formexportreport.h \
		genericFunctions.h \
		qcustomplot.h \
		accountwidget.H \
		formdescomposicion.h \
		stackwidget.H \
		stackvariablesexogenas.h \
		variableexogenawidget.h \
		stackencadenamientos.h \
		encadenamientoswidget.h \
		stackpreciosnohomogeneos.h \
		variablepnh.h \
		Eigen/Eigen \
		Eigen/Dense \
		Eigen/Core \
		Eigen/src/Core/util/DisableStupidWarnings.h \
		Eigen/src/Core/util/Macros.h \
		Eigen/src/Core/util/MKL_support.h \
		Eigen/src/Core/util/Constants.h \
		Eigen/src/Core/util/ForwardDeclarations.h \
		Eigen/src/Core/util/Meta.h \
		Eigen/src/Core/util/StaticAssert.h \
		Eigen/src/Core/util/XprHelper.h \
		Eigen/src/Core/util/Memory.h \
		Eigen/src/Core/NumTraits.h \
		Eigen/src/Core/MathFunctions.h \
		Eigen/src/Core/GenericPacketMath.h \
		Eigen/src/Core/arch/SSE/PacketMath.h \
		Eigen/src/Core/arch/SSE/MathFunctions.h \
		Eigen/src/Core/arch/SSE/Complex.h \
		Eigen/src/Core/arch/AltiVec/PacketMath.h \
		Eigen/src/Core/arch/AltiVec/Complex.h \
		Eigen/src/Core/arch/NEON/PacketMath.h \
		Eigen/src/Core/arch/NEON/Complex.h \
		Eigen/src/Core/arch/Default/Settings.h \
		Eigen/src/Core/Functors.h \
		Eigen/src/Core/DenseCoeffsBase.h \
		Eigen/src/Core/DenseBase.h \
		Eigen/src/plugins/BlockMethods.h \
		Eigen/src/Core/MatrixBase.h \
		Eigen/src/plugins/CommonCwiseUnaryOps.h \
		Eigen/src/plugins/CommonCwiseBinaryOps.h \
		Eigen/src/plugins/MatrixCwiseUnaryOps.h \
		Eigen/src/plugins/MatrixCwiseBinaryOps.h \
		Eigen/src/Core/EigenBase.h \
		Eigen/src/Core/Assign.h \
		Eigen/src/Core/util/BlasUtil.h \
		Eigen/src/Core/DenseStorage.h \
		Eigen/src/Core/NestByValue.h \
		Eigen/src/Core/ForceAlignedAccess.h \
		Eigen/src/Core/ReturnByValue.h \
		Eigen/src/Core/NoAlias.h \
		Eigen/src/Core/PlainObjectBase.h \
		Eigen/src/Core/Matrix.h \
		Eigen/src/Core/Array.h \
		Eigen/src/Core/CwiseBinaryOp.h \
		Eigen/src/Core/CwiseUnaryOp.h \
		Eigen/src/Core/CwiseNullaryOp.h \
		Eigen/src/Core/CwiseUnaryView.h \
		Eigen/src/Core/SelfCwiseBinaryOp.h \
		Eigen/src/Core/Dot.h \
		Eigen/src/Core/StableNorm.h \
		Eigen/src/Core/MapBase.h \
		Eigen/src/Core/Stride.h \
		Eigen/src/Core/Map.h \
		Eigen/src/Core/Block.h \
		Eigen/src/Core/VectorBlock.h \
		Eigen/src/Core/Ref.h \
		Eigen/src/Core/Transpose.h \
		Eigen/src/Core/DiagonalMatrix.h \
		Eigen/src/Core/Diagonal.h \
		Eigen/src/Core/DiagonalProduct.h \
		Eigen/src/Core/PermutationMatrix.h \
		Eigen/src/Core/Transpositions.h \
		Eigen/src/Core/Redux.h \
		Eigen/src/Core/Visitor.h \
		Eigen/src/Core/Fuzzy.h \
		Eigen/src/Core/IO.h \
		Eigen/src/Core/Swap.h \
		Eigen/src/Core/CommaInitializer.h \
		Eigen/src/Core/Flagged.h \
		Eigen/src/Core/ProductBase.h \
		Eigen/src/Core/GeneralProduct.h \
		Eigen/src/Core/TriangularMatrix.h \
		Eigen/src/Core/SelfAdjointView.h \
		Eigen/src/Core/products/GeneralBlockPanelKernel.h \
		Eigen/src/Core/products/Parallelizer.h \
		Eigen/src/Core/products/CoeffBasedProduct.h \
		Eigen/src/Core/products/GeneralMatrixVector.h \
		Eigen/src/Core/products/GeneralMatrixMatrix.h \
		Eigen/src/Core/SolveTriangular.h \
		Eigen/src/Core/products/GeneralMatrixMatrixTriangular.h \
		Eigen/src/Core/products/SelfadjointMatrixVector.h \
		Eigen/src/Core/products/SelfadjointMatrixMatrix.h \
		Eigen/src/Core/products/SelfadjointProduct.h \
		Eigen/src/Core/products/SelfadjointRank2Update.h \
		Eigen/src/Core/products/TriangularMatrixVector.h \
		Eigen/src/Core/products/TriangularMatrixMatrix.h \
		Eigen/src/Core/products/TriangularSolverMatrix.h \
		Eigen/src/Core/products/TriangularSolverVector.h \
		Eigen/src/Core/BandMatrix.h \
		Eigen/src/Core/CoreIterators.h \
		Eigen/src/Core/BooleanRedux.h \
		Eigen/src/Core/Select.h \
		Eigen/src/Core/VectorwiseOp.h \
		Eigen/src/Core/Random.h \
		Eigen/src/Core/Replicate.h \
		Eigen/src/Core/Reverse.h \
		Eigen/src/Core/ArrayBase.h \
		Eigen/src/plugins/ArrayCwiseUnaryOps.h \
		Eigen/src/plugins/ArrayCwiseBinaryOps.h \
		Eigen/src/Core/ArrayWrapper.h \
		Eigen/src/Core/products/GeneralMatrixMatrix_MKL.h \
		Eigen/src/Core/products/GeneralMatrixVector_MKL.h \
		Eigen/src/Core/products/GeneralMatrixMatrixTriangular_MKL.h \
		Eigen/src/Core/products/SelfadjointMatrixMatrix_MKL.h \
		Eigen/src/Core/products/SelfadjointMatrixVector_MKL.h \
		Eigen/src/Core/products/TriangularMatrixMatrix_MKL.h \
		Eigen/src/Core/products/TriangularMatrixVector_MKL.h \
		Eigen/src/Core/products/TriangularSolverMatrix_MKL.h \
		Eigen/src/Core/Assign_MKL.h \
		Eigen/src/Core/GlobalFunctions.h \
		Eigen/src/Core/util/ReenableStupidWarnings.h \
		Eigen/Eigen2Support \
		Eigen/src/Eigen2Support/Macros.h \
		Eigen/src/Eigen2Support/Memory.h \
		Eigen/src/Eigen2Support/Meta.h \
		Eigen/src/Eigen2Support/Lazy.h \
		Eigen/src/Eigen2Support/Cwise.h \
		Eigen/src/Eigen2Support/CwiseOperators.h \
		Eigen/src/Eigen2Support/TriangularSolver.h \
		Eigen/src/Eigen2Support/Block.h \
		Eigen/src/Eigen2Support/VectorBlock.h \
		Eigen/src/Eigen2Support/Minor.h \
		Eigen/src/Eigen2Support/MathFunctions.h \
		Eigen/LU \
		Eigen/src/misc/Solve.h \
		Eigen/src/misc/Kernel.h \
		Eigen/src/misc/Image.h \
		Eigen/src/LU/FullPivLU.h \
		Eigen/src/LU/PartialPivLU.h \
		Eigen/src/LU/PartialPivLU_MKL.h \
		Eigen/src/LU/Determinant.h \
		Eigen/src/LU/Inverse.h \
		Eigen/src/LU/arch/Inverse_SSE.h \
		Eigen/src/Eigen2Support/LU.h \
		Eigen/Cholesky \
		Eigen/src/Cholesky/LLT.h \
		Eigen/src/Cholesky/LDLT.h \
		Eigen/src/Cholesky/LLT_MKL.h \
		Eigen/QR \
		Eigen/Jacobi \
		Eigen/src/Jacobi/Jacobi.h \
		Eigen/Householder \
		Eigen/src/Householder/Householder.h \
		Eigen/src/Householder/HouseholderSequence.h \
		Eigen/src/Householder/BlockHouseholder.h \
		Eigen/src/QR/HouseholderQR.h \
		Eigen/src/QR/FullPivHouseholderQR.h \
		Eigen/src/QR/ColPivHouseholderQR.h \
		Eigen/src/QR/HouseholderQR_MKL.h \
		Eigen/src/QR/ColPivHouseholderQR_MKL.h \
		Eigen/src/Eigen2Support/QR.h \
		Eigen/Eigenvalues \
		Eigen/Geometry \
		Eigen/SVD \
		Eigen/src/SVD/JacobiSVD.h \
		Eigen/src/SVD/JacobiSVD_MKL.h \
		Eigen/src/SVD/UpperBidiagonalization.h \
		Eigen/src/Eigen2Support/SVD.h \
		Eigen/src/Geometry/OrthoMethods.h \
		Eigen/src/Geometry/EulerAngles.h \
		Eigen/src/Geometry/Homogeneous.h \
		Eigen/src/Geometry/RotationBase.h \
		Eigen/src/Geometry/Rotation2D.h \
		Eigen/src/Geometry/Quaternion.h \
		Eigen/src/Geometry/AngleAxis.h \
		Eigen/src/Geometry/Transform.h \
		Eigen/src/Geometry/Translation.h \
		Eigen/src/Geometry/Scaling.h \
		Eigen/src/Geometry/Hyperplane.h \
		Eigen/src/Geometry/ParametrizedLine.h \
		Eigen/src/Geometry/AlignedBox.h \
		Eigen/src/Geometry/Umeyama.h \
		Eigen/src/Geometry/arch/Geometry_SSE.h \
		Eigen/src/Eigen2Support/Geometry/All.h \
		Eigen/src/Eigen2Support/Geometry/RotationBase.h \
		Eigen/src/Eigen2Support/Geometry/Rotation2D.h \
		Eigen/src/Eigen2Support/Geometry/Quaternion.h \
		Eigen/src/Eigen2Support/Geometry/AngleAxis.h \
		Eigen/src/Eigen2Support/Geometry/Transform.h \
		Eigen/src/Eigen2Support/Geometry/Translation.h \
		Eigen/src/Eigen2Support/Geometry/Scaling.h \
		Eigen/src/Eigen2Support/Geometry/AlignedBox.h \
		Eigen/src/Eigen2Support/Geometry/Hyperplane.h \
		Eigen/src/Eigen2Support/Geometry/ParametrizedLine.h \
		Eigen/src/Eigenvalues/Tridiagonalization.h \
		Eigen/src/Eigenvalues/RealSchur.h \
		Eigen/src/Eigenvalues/HessenbergDecomposition.h \
		Eigen/src/Eigenvalues/EigenSolver.h \
		Eigen/src/Eigenvalues/SelfAdjointEigenSolver.h \
		Eigen/src/Eigenvalues/GeneralizedSelfAdjointEigenSolver.h \
		Eigen/src/Eigenvalues/ComplexSchur.h \
		Eigen/src/Eigenvalues/ComplexEigenSolver.h \
		Eigen/src/Eigenvalues/RealQZ.h \
		Eigen/src/Eigenvalues/GeneralizedEigenSolver.h \
		Eigen/src/Eigenvalues/MatrixBaseEigenvalues.h \
		Eigen/src/Eigenvalues/RealSchur_MKL.h \
		Eigen/src/Eigenvalues/ComplexSchur_MKL.h \
		Eigen/src/Eigenvalues/SelfAdjointEigenSolver_MKL.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.C

main.o: main.C mainwindow.H \
		formloadmatrix.H \
		ui_formLoadMatrix.h \
		formviewmatrix.H \
		formvariablesexogenas.h \
		formexportmatrix.h \
		formencadenamientos.h \
		ui_formcompararresultados.h \
		formcompararresultados.h \
		ui_formcompararmnc.h \
		formcompararmnc.h \
		ui_formincidenciai.h \
		formincidenciai.h \
		formpreciosnohomogeneos.h \
		formexportreport.h \
		ui_formexportreport.h \
		genericFunctions.h \
		qcustomplot.h \
		accountwidget.H \
		formdescomposicion.h \
		stackwidget.H \
		stackvariablesexogenas.h \
		variableexogenawidget.h \
		stackencadenamientos.h \
		encadenamientoswidget.h \
		stackpreciosnohomogeneos.h \
		variablepnh.h \
		Eigen/Eigen \
		Eigen/Dense \
		Eigen/Core \
		Eigen/src/Core/util/DisableStupidWarnings.h \
		Eigen/src/Core/util/Macros.h \
		Eigen/src/Core/util/MKL_support.h \
		Eigen/src/Core/util/Constants.h \
		Eigen/src/Core/util/ForwardDeclarations.h \
		Eigen/src/Core/util/Meta.h \
		Eigen/src/Core/util/StaticAssert.h \
		Eigen/src/Core/util/XprHelper.h \
		Eigen/src/Core/util/Memory.h \
		Eigen/src/Core/NumTraits.h \
		Eigen/src/Core/MathFunctions.h \
		Eigen/src/Core/GenericPacketMath.h \
		Eigen/src/Core/arch/SSE/PacketMath.h \
		Eigen/src/Core/arch/SSE/MathFunctions.h \
		Eigen/src/Core/arch/SSE/Complex.h \
		Eigen/src/Core/arch/AltiVec/PacketMath.h \
		Eigen/src/Core/arch/AltiVec/Complex.h \
		Eigen/src/Core/arch/NEON/PacketMath.h \
		Eigen/src/Core/arch/NEON/Complex.h \
		Eigen/src/Core/arch/Default/Settings.h \
		Eigen/src/Core/Functors.h \
		Eigen/src/Core/DenseCoeffsBase.h \
		Eigen/src/Core/DenseBase.h \
		Eigen/src/plugins/BlockMethods.h \
		Eigen/src/Core/MatrixBase.h \
		Eigen/src/plugins/CommonCwiseUnaryOps.h \
		Eigen/src/plugins/CommonCwiseBinaryOps.h \
		Eigen/src/plugins/MatrixCwiseUnaryOps.h \
		Eigen/src/plugins/MatrixCwiseBinaryOps.h \
		Eigen/src/Core/EigenBase.h \
		Eigen/src/Core/Assign.h \
		Eigen/src/Core/util/BlasUtil.h \
		Eigen/src/Core/DenseStorage.h \
		Eigen/src/Core/NestByValue.h \
		Eigen/src/Core/ForceAlignedAccess.h \
		Eigen/src/Core/ReturnByValue.h \
		Eigen/src/Core/NoAlias.h \
		Eigen/src/Core/PlainObjectBase.h \
		Eigen/src/Core/Matrix.h \
		Eigen/src/Core/Array.h \
		Eigen/src/Core/CwiseBinaryOp.h \
		Eigen/src/Core/CwiseUnaryOp.h \
		Eigen/src/Core/CwiseNullaryOp.h \
		Eigen/src/Core/CwiseUnaryView.h \
		Eigen/src/Core/SelfCwiseBinaryOp.h \
		Eigen/src/Core/Dot.h \
		Eigen/src/Core/StableNorm.h \
		Eigen/src/Core/MapBase.h \
		Eigen/src/Core/Stride.h \
		Eigen/src/Core/Map.h \
		Eigen/src/Core/Block.h \
		Eigen/src/Core/VectorBlock.h \
		Eigen/src/Core/Ref.h \
		Eigen/src/Core/Transpose.h \
		Eigen/src/Core/DiagonalMatrix.h \
		Eigen/src/Core/Diagonal.h \
		Eigen/src/Core/DiagonalProduct.h \
		Eigen/src/Core/PermutationMatrix.h \
		Eigen/src/Core/Transpositions.h \
		Eigen/src/Core/Redux.h \
		Eigen/src/Core/Visitor.h \
		Eigen/src/Core/Fuzzy.h \
		Eigen/src/Core/IO.h \
		Eigen/src/Core/Swap.h \
		Eigen/src/Core/CommaInitializer.h \
		Eigen/src/Core/Flagged.h \
		Eigen/src/Core/ProductBase.h \
		Eigen/src/Core/GeneralProduct.h \
		Eigen/src/Core/TriangularMatrix.h \
		Eigen/src/Core/SelfAdjointView.h \
		Eigen/src/Core/products/GeneralBlockPanelKernel.h \
		Eigen/src/Core/products/Parallelizer.h \
		Eigen/src/Core/products/CoeffBasedProduct.h \
		Eigen/src/Core/products/GeneralMatrixVector.h \
		Eigen/src/Core/products/GeneralMatrixMatrix.h \
		Eigen/src/Core/SolveTriangular.h \
		Eigen/src/Core/products/GeneralMatrixMatrixTriangular.h \
		Eigen/src/Core/products/SelfadjointMatrixVector.h \
		Eigen/src/Core/products/SelfadjointMatrixMatrix.h \
		Eigen/src/Core/products/SelfadjointProduct.h \
		Eigen/src/Core/products/SelfadjointRank2Update.h \
		Eigen/src/Core/products/TriangularMatrixVector.h \
		Eigen/src/Core/products/TriangularMatrixMatrix.h \
		Eigen/src/Core/products/TriangularSolverMatrix.h \
		Eigen/src/Core/products/TriangularSolverVector.h \
		Eigen/src/Core/BandMatrix.h \
		Eigen/src/Core/CoreIterators.h \
		Eigen/src/Core/BooleanRedux.h \
		Eigen/src/Core/Select.h \
		Eigen/src/Core/VectorwiseOp.h \
		Eigen/src/Core/Random.h \
		Eigen/src/Core/Replicate.h \
		Eigen/src/Core/Reverse.h \
		Eigen/src/Core/ArrayBase.h \
		Eigen/src/plugins/ArrayCwiseUnaryOps.h \
		Eigen/src/plugins/ArrayCwiseBinaryOps.h \
		Eigen/src/Core/ArrayWrapper.h \
		Eigen/src/Core/products/GeneralMatrixMatrix_MKL.h \
		Eigen/src/Core/products/GeneralMatrixVector_MKL.h \
		Eigen/src/Core/products/GeneralMatrixMatrixTriangular_MKL.h \
		Eigen/src/Core/products/SelfadjointMatrixMatrix_MKL.h \
		Eigen/src/Core/products/SelfadjointMatrixVector_MKL.h \
		Eigen/src/Core/products/TriangularMatrixMatrix_MKL.h \
		Eigen/src/Core/products/TriangularMatrixVector_MKL.h \
		Eigen/src/Core/products/TriangularSolverMatrix_MKL.h \
		Eigen/src/Core/Assign_MKL.h \
		Eigen/src/Core/GlobalFunctions.h \
		Eigen/src/Core/util/ReenableStupidWarnings.h \
		Eigen/Eigen2Support \
		Eigen/src/Eigen2Support/Macros.h \
		Eigen/src/Eigen2Support/Memory.h \
		Eigen/src/Eigen2Support/Meta.h \
		Eigen/src/Eigen2Support/Lazy.h \
		Eigen/src/Eigen2Support/Cwise.h \
		Eigen/src/Eigen2Support/CwiseOperators.h \
		Eigen/src/Eigen2Support/TriangularSolver.h \
		Eigen/src/Eigen2Support/Block.h \
		Eigen/src/Eigen2Support/VectorBlock.h \
		Eigen/src/Eigen2Support/Minor.h \
		Eigen/src/Eigen2Support/MathFunctions.h \
		Eigen/LU \
		Eigen/src/misc/Solve.h \
		Eigen/src/misc/Kernel.h \
		Eigen/src/misc/Image.h \
		Eigen/src/LU/FullPivLU.h \
		Eigen/src/LU/PartialPivLU.h \
		Eigen/src/LU/PartialPivLU_MKL.h \
		Eigen/src/LU/Determinant.h \
		Eigen/src/LU/Inverse.h \
		Eigen/src/LU/arch/Inverse_SSE.h \
		Eigen/src/Eigen2Support/LU.h \
		Eigen/Cholesky \
		Eigen/src/Cholesky/LLT.h \
		Eigen/src/Cholesky/LDLT.h \
		Eigen/src/Cholesky/LLT_MKL.h \
		Eigen/QR \
		Eigen/Jacobi \
		Eigen/src/Jacobi/Jacobi.h \
		Eigen/Householder \
		Eigen/src/Householder/Householder.h \
		Eigen/src/Householder/HouseholderSequence.h \
		Eigen/src/Householder/BlockHouseholder.h \
		Eigen/src/QR/HouseholderQR.h \
		Eigen/src/QR/FullPivHouseholderQR.h \
		Eigen/src/QR/ColPivHouseholderQR.h \
		Eigen/src/QR/HouseholderQR_MKL.h \
		Eigen/src/QR/ColPivHouseholderQR_MKL.h \
		Eigen/src/Eigen2Support/QR.h \
		Eigen/Eigenvalues \
		Eigen/Geometry \
		Eigen/SVD \
		Eigen/src/SVD/JacobiSVD.h \
		Eigen/src/SVD/JacobiSVD_MKL.h \
		Eigen/src/SVD/UpperBidiagonalization.h \
		Eigen/src/Eigen2Support/SVD.h \
		Eigen/src/Geometry/OrthoMethods.h \
		Eigen/src/Geometry/EulerAngles.h \
		Eigen/src/Geometry/Homogeneous.h \
		Eigen/src/Geometry/RotationBase.h \
		Eigen/src/Geometry/Rotation2D.h \
		Eigen/src/Geometry/Quaternion.h \
		Eigen/src/Geometry/AngleAxis.h \
		Eigen/src/Geometry/Transform.h \
		Eigen/src/Geometry/Translation.h \
		Eigen/src/Geometry/Scaling.h \
		Eigen/src/Geometry/Hyperplane.h \
		Eigen/src/Geometry/ParametrizedLine.h \
		Eigen/src/Geometry/AlignedBox.h \
		Eigen/src/Geometry/Umeyama.h \
		Eigen/src/Geometry/arch/Geometry_SSE.h \
		Eigen/src/Eigen2Support/Geometry/All.h \
		Eigen/src/Eigen2Support/Geometry/RotationBase.h \
		Eigen/src/Eigen2Support/Geometry/Rotation2D.h \
		Eigen/src/Eigen2Support/Geometry/Quaternion.h \
		Eigen/src/Eigen2Support/Geometry/AngleAxis.h \
		Eigen/src/Eigen2Support/Geometry/Transform.h \
		Eigen/src/Eigen2Support/Geometry/Translation.h \
		Eigen/src/Eigen2Support/Geometry/Scaling.h \
		Eigen/src/Eigen2Support/Geometry/AlignedBox.h \
		Eigen/src/Eigen2Support/Geometry/Hyperplane.h \
		Eigen/src/Eigen2Support/Geometry/ParametrizedLine.h \
		Eigen/src/Eigenvalues/Tridiagonalization.h \
		Eigen/src/Eigenvalues/RealSchur.h \
		Eigen/src/Eigenvalues/HessenbergDecomposition.h \
		Eigen/src/Eigenvalues/EigenSolver.h \
		Eigen/src/Eigenvalues/SelfAdjointEigenSolver.h \
		Eigen/src/Eigenvalues/GeneralizedSelfAdjointEigenSolver.h \
		Eigen/src/Eigenvalues/ComplexSchur.h \
		Eigen/src/Eigenvalues/ComplexEigenSolver.h \
		Eigen/src/Eigenvalues/RealQZ.h \
		Eigen/src/Eigenvalues/GeneralizedEigenSolver.h \
		Eigen/src/Eigenvalues/MatrixBaseEigenvalues.h \
		Eigen/src/Eigenvalues/RealSchur_MKL.h \
		Eigen/src/Eigenvalues/ComplexSchur_MKL.h \
		Eigen/src/Eigenvalues/SelfAdjointEigenSolver_MKL.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.C

formloadmatrix.o: formloadmatrix.C formloadmatrix.H \
		ui_formLoadMatrix.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o formloadmatrix.o formloadmatrix.C

formviewmatrix.o: formviewmatrix.C formviewmatrix.H \
		ui_formViewMatrix.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o formviewmatrix.o formviewmatrix.C

stackwidget.o: stackwidget.C stackwidget.H \
		accountwidget.H
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o stackwidget.o stackwidget.C

accountwidget.o: accountwidget.C accountwidget.H
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o accountwidget.o accountwidget.C

formvariablesexogenas.o: formvariablesexogenas.cpp formvariablesexogenas.h \
		ui_formvariablesexogenas.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o formvariablesexogenas.o formvariablesexogenas.cpp

stackvariablesexogenas.o: stackvariablesexogenas.cpp stackvariablesexogenas.h \
		variableexogenawidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o stackvariablesexogenas.o stackvariablesexogenas.cpp

variableexogenawidget.o: variableexogenawidget.cpp variableexogenawidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o variableexogenawidget.o variableexogenawidget.cpp

formexportmatrix.o: formexportmatrix.cpp formexportmatrix.h \
		ui_formexportmatrix.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o formexportmatrix.o formexportmatrix.cpp

formencadenamientos.o: formencadenamientos.cpp formencadenamientos.h \
		ui_formencadenamientos.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o formencadenamientos.o formencadenamientos.cpp

stackencadenamientos.o: stackencadenamientos.cpp stackencadenamientos.h \
		encadenamientoswidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o stackencadenamientos.o stackencadenamientos.cpp

encadenamientoswidget.o: encadenamientoswidget.cpp encadenamientoswidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o encadenamientoswidget.o encadenamientoswidget.cpp

formcompararresultados.o: formcompararresultados.cpp formcompararresultados.h \
		ui_formcompararresultados.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o formcompararresultados.o formcompararresultados.cpp

formcompararmnc.o: formcompararmnc.cpp formcompararmnc.h \
		ui_formcompararmnc.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o formcompararmnc.o formcompararmnc.cpp

formincidenciai.o: formincidenciai.cpp formincidenciai.h \
		ui_formincidenciai.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o formincidenciai.o formincidenciai.cpp

formpreciosnohomogeneos.o: formpreciosnohomogeneos.cpp formpreciosnohomogeneos.h \
		ui_formpreciosnohomogeneos.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o formpreciosnohomogeneos.o formpreciosnohomogeneos.cpp

stackpreciosnohomogeneos.o: stackpreciosnohomogeneos.cpp stackpreciosnohomogeneos.h \
		variablepnh.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o stackpreciosnohomogeneos.o stackpreciosnohomogeneos.cpp

variablepnh.o: variablepnh.cpp variablepnh.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o variablepnh.o variablepnh.cpp

genericFunctions.o: genericFunctions.cpp genericFunctions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o genericFunctions.o genericFunctions.cpp

formexportreport.o: formexportreport.cpp formexportreport.h \
		ui_formexportreport.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o formexportreport.o formexportreport.cpp

qcustomplot.o: qcustomplot.cpp qcustomplot.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qcustomplot.o qcustomplot.cpp

formdescomposicion.o: formdescomposicion.cpp formdescomposicion.h \
		ui_formdescomposicion.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o formdescomposicion.o formdescomposicion.cpp

qrc_images.o: qrc_images.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_images.o qrc_images.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_formloadmatrix.o: moc_formloadmatrix.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_formloadmatrix.o moc_formloadmatrix.cpp

moc_formviewmatrix.o: moc_formviewmatrix.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_formviewmatrix.o moc_formviewmatrix.cpp

moc_stackwidget.o: moc_stackwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_stackwidget.o moc_stackwidget.cpp

moc_accountwidget.o: moc_accountwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_accountwidget.o moc_accountwidget.cpp

moc_formvariablesexogenas.o: moc_formvariablesexogenas.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_formvariablesexogenas.o moc_formvariablesexogenas.cpp

moc_stackvariablesexogenas.o: moc_stackvariablesexogenas.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_stackvariablesexogenas.o moc_stackvariablesexogenas.cpp

moc_variableexogenawidget.o: moc_variableexogenawidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_variableexogenawidget.o moc_variableexogenawidget.cpp

moc_formexportmatrix.o: moc_formexportmatrix.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_formexportmatrix.o moc_formexportmatrix.cpp

moc_formencadenamientos.o: moc_formencadenamientos.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_formencadenamientos.o moc_formencadenamientos.cpp

moc_stackencadenamientos.o: moc_stackencadenamientos.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_stackencadenamientos.o moc_stackencadenamientos.cpp

moc_encadenamientoswidget.o: moc_encadenamientoswidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_encadenamientoswidget.o moc_encadenamientoswidget.cpp

moc_formcompararresultados.o: moc_formcompararresultados.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_formcompararresultados.o moc_formcompararresultados.cpp

moc_formcompararmnc.o: moc_formcompararmnc.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_formcompararmnc.o moc_formcompararmnc.cpp

moc_formincidenciai.o: moc_formincidenciai.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_formincidenciai.o moc_formincidenciai.cpp

moc_formpreciosnohomogeneos.o: moc_formpreciosnohomogeneos.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_formpreciosnohomogeneos.o moc_formpreciosnohomogeneos.cpp

moc_stackpreciosnohomogeneos.o: moc_stackpreciosnohomogeneos.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_stackpreciosnohomogeneos.o moc_stackpreciosnohomogeneos.cpp

moc_variablepnh.o: moc_variablepnh.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_variablepnh.o moc_variablepnh.cpp

moc_formexportreport.o: moc_formexportreport.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_formexportreport.o moc_formexportreport.cpp

moc_qcustomplot.o: moc_qcustomplot.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qcustomplot.o moc_qcustomplot.cpp

moc_formdescomposicion.o: moc_formdescomposicion.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_formdescomposicion.o moc_formdescomposicion.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

