#############################################################################
# Makefile for building: SMSAM
# Generated by qmake (2.01a) (Qt 4.6.3) on: vie abr 17 11:59:55 2015
# Project:  SMSAM.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile SMSAM.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = mainwindow.C \
		main.C \
		formloadmatrix.C \
		formviewmatrix.C \
		stackwidget.C \
		accountwidget.C moc_mainwindow.cpp \
		moc_formloadmatrix.cpp \
		moc_formviewmatrix.cpp \
		moc_stackwidget.cpp \
		moc_accountwidget.cpp
OBJECTS       = mainwindow.o \
		main.o \
		formloadmatrix.o \
		formviewmatrix.o \
		stackwidget.o \
		accountwidget.o \
		moc_mainwindow.o \
		moc_formloadmatrix.o \
		moc_formviewmatrix.o \
		moc_stackwidget.o \
		moc_accountwidget.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		SMSAM.pro
QMAKE_TARGET  = SMSAM
DESTDIR       = 
TARGET        = SMSAM

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_formLoadMatrix.h ui_formMatrixView.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: SMSAM.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile SMSAM.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile SMSAM.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/SMSAM1.0.0 || $(MKDIR) .tmp/SMSAM1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/SMSAM1.0.0/ && $(COPY_FILE) --parents mainwindow.H formloadmatrix.H formviewmatrix.H stackwidget.H accountwidget.H .tmp/SMSAM1.0.0/ && $(COPY_FILE) --parents mainwindow.C main.C formloadmatrix.C formviewmatrix.C stackwidget.C accountwidget.C .tmp/SMSAM1.0.0/ && $(COPY_FILE) --parents formLoadMatrix.ui formMatrixView.ui .tmp/SMSAM1.0.0/ && (cd `dirname .tmp/SMSAM1.0.0` && $(TAR) SMSAM1.0.0.tar SMSAM1.0.0 && $(COMPRESS) SMSAM1.0.0.tar) && $(MOVE) `dirname .tmp/SMSAM1.0.0`/SMSAM1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/SMSAM1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_formloadmatrix.cpp moc_formviewmatrix.cpp moc_stackwidget.cpp moc_accountwidget.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_formloadmatrix.cpp moc_formviewmatrix.cpp moc_stackwidget.cpp moc_accountwidget.cpp
moc_mainwindow.cpp: formloadmatrix.H \
		ui_formLoadMatrix.h \
		formviewmatrix.H \
		ui_formMatrixView.h \
		stackwidget.H \
		accountwidget.H \
		mainwindow.H
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) mainwindow.H -o moc_mainwindow.cpp

moc_formloadmatrix.cpp: ui_formLoadMatrix.h \
		formloadmatrix.H
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) formloadmatrix.H -o moc_formloadmatrix.cpp

moc_formviewmatrix.cpp: ui_formMatrixView.h \
		formviewmatrix.H
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) formviewmatrix.H -o moc_formviewmatrix.cpp

moc_stackwidget.cpp: accountwidget.H \
		stackwidget.H
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) stackwidget.H -o moc_stackwidget.cpp

moc_accountwidget.cpp: accountwidget.H
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) accountwidget.H -o moc_accountwidget.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_formLoadMatrix.h ui_formMatrixView.h
compiler_uic_clean:
	-$(DEL_FILE) ui_formLoadMatrix.h ui_formMatrixView.h
ui_formLoadMatrix.h: formLoadMatrix.ui
	/usr/bin/uic-qt4 formLoadMatrix.ui -o ui_formLoadMatrix.h

ui_formMatrixView.h: formMatrixView.ui
	/usr/bin/uic-qt4 formMatrixView.ui -o ui_formMatrixView.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

mainwindow.o: mainwindow.C mainwindow.H \
		formloadmatrix.H \
		ui_formLoadMatrix.h \
		formviewmatrix.H \
		ui_formMatrixView.h \
		stackwidget.H \
		accountwidget.H
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.C

main.o: main.C mainwindow.H \
		formloadmatrix.H \
		ui_formLoadMatrix.h \
		formviewmatrix.H \
		ui_formMatrixView.h \
		stackwidget.H \
		accountwidget.H
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.C

formloadmatrix.o: formloadmatrix.C formloadmatrix.H \
		ui_formLoadMatrix.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o formloadmatrix.o formloadmatrix.C

formviewmatrix.o: formviewmatrix.C formviewmatrix.H \
		ui_formMatrixView.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o formviewmatrix.o formviewmatrix.C

stackwidget.o: stackwidget.C stackwidget.H \
		accountwidget.H
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o stackwidget.o stackwidget.C

accountwidget.o: accountwidget.C accountwidget.H
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o accountwidget.o accountwidget.C

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_formloadmatrix.o: moc_formloadmatrix.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_formloadmatrix.o moc_formloadmatrix.cpp

moc_formviewmatrix.o: moc_formviewmatrix.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_formviewmatrix.o moc_formviewmatrix.cpp

moc_stackwidget.o: moc_stackwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_stackwidget.o moc_stackwidget.cpp

moc_accountwidget.o: moc_accountwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_accountwidget.o moc_accountwidget.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

